# Generated by Django 4.2.4 on 2024-03-10 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0002_markatt'),
    ]

    operations = [
        migrations.CreateModel(
            name='FacultyLogin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fac_name', models.CharField(max_length=100)),
                ('fac_pass', models.CharField(max_length=100)),
            ],
        ),
    ]
