# Generated by Django 4.2.4 on 2024-04-01 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0005_notice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notice',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
