# Generated by Django 4.2.4 on 2024-04-01 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0006_alter_notice_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absentnote',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
