# Generated by Django 4.2.4 on 2024-04-01 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0007_alter_absentnote_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='absentnote',
            name='user_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.userdetails'),
        ),
    ]
