# Generated by Django 4.2.4 on 2024-04-03 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0009_remove_absentnote_user_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='markatt',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='attendance_images/'),
        ),
    ]
