# Generated by Django 4.2.4 on 2024-04-03 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0010_markatt_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markatt',
            name='image',
        ),
    ]
