# Generated by Django 4.2.4 on 2024-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0012_remove_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
