# Generated by Django 4.2.4 on 2024-04-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0013_notice_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='markatt',
            name='existing_photo',
            field=models.ImageField(null=True, upload_to='existing_photos/'),
        ),
    ]
