# Generated by Django 4.2.4 on 2024-04-04 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0014_markatt_existing_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='markatt',
            name='existing_photo',
        ),
    ]
