# Generated by Django 4.2.4 on 2024-04-10 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Student', '0015_remove_markatt_existing_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100, null=True)),
                ('date', models.DateField(null=True)),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='timeslot_photos')),
                ('latitude', models.TextField(null=True)),
                ('longitude', models.TextField(null=True)),
            ],
        ),
    ]
